---
name: JDTLS Deploy in Personal Mason Registry

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      JDTLS_VERSION:
        description: "jdtls version"
        required: false
      FORCE_REPACKAGE:
        description: "Replace package already exists"
        required: true
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  check-and-deploy:
    env:
      JDTLS_VERSION: ${{ github.event.inputs.JDTLS_VERSION }}
      FORCE_REPACKAGE: ${{ github.event.inputs.FORCE_REPACKAGE }}
      GITHUB_TOKEN: ${{ secrets.PMR_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set the latest jdtls version
        if: env.JDTLS_VERSION == ''
        run: |
          echo "JDTLS_VERSION=$(curl -s -H 'Accept: application/vnd.github.v3+json' 'https://api.github.com/repos/${{ github.repository }}/releases' | jq -r '.[].tag_name')" >> $GITHUB_ENV

      - name: deploy in personal mason registry
        if: env.JDTLS_VERSION != ''
        run: |

          git clone https://indika-dev:${{ secrets.PMR_TOKEN }}@github.com/indika-dev/personal-mason-registry.git

          cd  personal-mason-registry/
          git config user.name "GHA Deploy in PMR"
          git config user.email "56093026+indika-dev@users.noreply.github.com"
          git remote set-url --push origin https://indika-dev:${{ secrets.PMR_TOKEN }}@github.com/indika-dev/personal-mason-registry.git

          cat >./packages/jdtls/package.yaml <<EOF
          name: jdtls
          description: Java language server.
          homepage: https://github.com/eclipse/eclipse.jdt.ls
          licenses:
            - EPL-2.0
          languages:
            - Java
          categories:
            - LSP

          source:
            # renovate:datasource=github-tags
            id: pkg:generic/eclipse/eclipse.jdt.ls@v${{env.JDTLS_VERSION}}
            download:
              - target: [darwin_x64, darwin_arm64]
                files:
                  jdtls.tar.gz: https://github.com/indika-dev/repackage-jdtls/releases/download/{{ version | strip_prefix "v" }}/jdtls.tar.gz
                  lombok.jar: https://projectlombok.org/downloads/lombok.jar
                config: config_mac/

              - target: [linux_x64, linux_x86]
                files:
                  jdtls.tar.gz: https://github.com/indika-dev/repackage-jdtls/releases/download/{{ version | strip_prefix "v" }}/jdtls.tar.gz
                  lombok.jar: https://projectlombok.org/downloads/lombok.jar
                config: config_linux/

              - target: linux_arm64
                files:
                  jdtls.tar.gz: https://github.com/indika-dev/repackage-jdtls/releases/download/{{ version | strip_prefix "v" }}/jdtls.tar.gz
                  lombok.jar: https://projectlombok.org/downloads/lombok.jar
                config: config_linux_arm/

              - target: win
                files:
                  jdtls.tar.gz: https://github.com/indika-dev/repackage-jdtls/releases/download/{{ version | strip_prefix "v" }}/jdtls.tar.gz
                  lombok.jar: https://projectlombok.org/downloads/lombok.jar
                config: config_win/

          schemas:
            lsp: vscode:https://raw.githubusercontent.com/redhat-developer/vscode-java/master/package.json

          bin:
            jdtls: python:bin/jdtls

          share:
            jdtls/lombok.jar: lombok.jar
            jdtls/plugins/: plugins/
            jdtls/plugins/org.eclipse.equinox.launcher.jar: plugins/org.eclipse.equinox.launcher.jar
            jdtls/config/: "{{source.download.config}}"
          EOF


          cat >./packages/vscode-spring-boot-tools/package.yaml <<EOF
          name: vscode-spring-boot-tools
          description: |
            VS Code Language Server for Spring Boot
            VSCode extension and Language Server providing support for working with Spring Boot application.properties, application.yml and .java files.

            Note: this extension has a dependency on VS Code extension of Language Support for Java™ by Red Hat
          homepage: https://github.com/spring-projects/sts4
          licenses:
            - EPL-1.0
          languages:
            - Java
          categories:
            - LSP

          source:
            id: pkg:openvsx/VMware/vscode-spring-boot@${{env.SBT_VERSION}}
            download:
              file: VMware.vscode-spring-boot-{{version}}.vsix

          schemas:
            lsp: vscode:https://raw.githubusercontent.com/spring-projects/sts4/master/vscode-extensions/vscode-spring-boot/package.json

          share:
            vscode-spring-boot-tools/jdtls/: extension/jars/
            vscode-spring-boot-tools/language-server.jar: extension/language-server/spring-boot-language-server-{{version}}-SNAPSHOT-exec.jar
          EOF

          git add -A
          if ! git diff-index --quiet HEAD; then
          git commit -m "bump jdtls->${{env.JDTLS_VERSION}} sbt->${{env.SBT_VERSION}}"
          git push
          else
          echo "No changes to commit"
          fi
